spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_postgres_db
    username: postgres
    password: pwd123

  flyway:
    schemas: credit_check
    enabled: true

app:
  inventory:
    data:
      path: src/main/resources/inventory_data.csv